src/Entity/Personne.php
<?php

namespace App\Entity;

use App\Repository\PersonneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PersonneRepository::class)]
class Personne
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $datenaissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $cin = null;

    #[ORM\OneToMany(mappedBy: 'personne', targetEntity: Voiture::class)]
    private Collection $voiture;

    public function __construct()
    {
        $this->voiture = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDatenaissance(): ?\DateTimeInterface
    {
        return $this->datenaissance;
    }

    public function setDatenaissance(\DateTimeInterface $datenaissance): self
    {
        $this->datenaissance = $datenaissance;

        return $this;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(?string $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    /**
     * @return Collection<int, Voiture>
     */
    public function getVoiture(): Collection
    {
        return $this->voiture;
    }

    public function addVoiture(Voiture $voiture): self
    {
        if (!$this->voiture->contains($voiture)) {
            $this->voiture->add($voiture);
            $voiture->setPersonne($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): self
    {
        if ($this->voiture->removeElement($voiture)) {
            // set the owning side to null (unless already changed)
            if ($voiture->getPersonne() === $this) {
                $voiture->setPersonne(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return $this->nom;
        
    }

}

src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $nb_porte = null;

    #[ORM\Column(nullable: true)]
    private ?int $puissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $kilometrage = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $marque = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $type = null;

    #[ORM\ManyToOne(inversedBy: 'voiture')]
    private ?Personne $personne = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbPorte(): ?int
    {
        return $this->nb_porte;
    }

    public function setNbPorte(?int $nb_porte): self
    {
        $this->nb_porte = $nb_porte;

        return $this;
    }

    public function getPuissance(): ?int
    {
        return $this->puissance;
    }

    public function setPuissance(?int $puissance): self
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getKilometrage(): ?string
    {
        return $this->kilometrage;
    }

    public function setKilometrage(?string $kilometrage): self
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(?string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPersonne(): ?Personne
    {
        return $this->personne;
    }

    public function setPersonne(?Personne $personne): self
    {
        $this->personne = $personne;

        return $this;
    }
    public function __toString(){
        return $this->id;
        
    }
}

src/Controller/PersonneController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Personne;
#use App\Form\PersonneType;

class PersonneController extends AbstractController
{
    #[Route('/', name: 'app_personne')]

    public function index(EntityManagerInterface $entityManager): Response
    {
        $productRepository = $entityManager->getRepository(Personne::class);
        $personnes = $productRepository->findAll();
        


        return $this->render('personne/index.html.twig', [
            'personnes'=>$personnes,
        ]);
    }
   
}

src/Controller/VoitureController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Voiture;

class VoitureController extends AbstractController
{
    #[Route('/voiture', name: 'app_voiture')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $productRepository = $entityManager->getRepository(Voiture::class);
        $voitures = $productRepository->findAll();
        


        return $this->render('voiture/index.html.twig', [
            'voitures'=>$voitures,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/personne/index.html.twig
{% block body %}
<h2> liste des personnes</h2>
 
 <table>
                         <thead>
						    <tr>
						      <th>nom</th>
						      <th>date_naissance</th>
						      <th>cin</th>
                              <th>voiture</th>
                              <th>Action</th>
						    </tr>
						  </thead>
                          <tbody>
                          {% for personne in personnes %}
                          <tr>
						      
						      <td>{{ personne.nom }}</td>
						      <td>{{ personne.datenaissance|date('d/m/Y') }}</td>
                              <td>{{ personne.cin }}</td>
                        <ul> 
                              <td>
                              {% for voiture in personne.voiture %}
                              
                              <li>{{ voiture.id }}</li>
                               {% endfor %}
                               
						     
                              <td>
                              <ul>
                              
                              <a href="#"><li>edit</li></a>
                              <a href="#"><li>delete</li></a>
                               
                              </ul>
                              </td>
                               
                             
                            </tr>
 
                          {% endfor %}
                      </tbody>
 
        
   
   
   </table> 
  <a href="#"> <button> ajouter personne</button></a>
{% endblock %}

templates/voiture/index.html.twig
{% block body %}
<h2> liste des voitures </h2>
 
 <table>
                         <thead>
						    <tr>
						      <th>Nb_porte</th>
						      <th>Puissance</th>
						      <th>Kilometrage</th>
                              <th>Marque</th>
                              <th>Type</th>
                              <th>Personne</th>
                              <th>action</th>
						    </tr>
						  </thead>
                          <tbody>
                          {% for voiture in voitures %}
                          <tr>
						      
						      <td>{{ voiture.nbPorte }}</td>
                              <td>{{ voiture.puissance }}</td>
                              <td>{{ voiture.kilometrage }}</td>
                              <td>{{ voiture.marque }}</td>
                              <td>{{ voiture.type }}</td>
                              <td>{{ voiture.personne }}</td>
						     <td>
                              <ul>
                              <a href="#"><li>edit</li></a>
                              <a href="#"><li>delete</li></a>
                               
                              </ul>
                              </td>
                               
                             
                            </tr>
 
                          {% endfor %}
                      </tbody>
 
        
   
   
   </table> 
  <a href="#"> <button> ajouter personne</button></a>
{% endblock %}